[package]
name    = "vms-sources"
version = "0.2.0"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
vms-core          = { path = "../vms-core" }
tokio             = { workspace = true }
tokio-util        = { workspace = true }
dashmap           = { workspace = true }
rumqttc           = { workspace = true }
tokio-tungstenite = { workspace = true }
futures           = { workspace = true }
notify            = { workspace = true }
reqwest           = { workspace = true }
uuid              = { workspace = true }
serde             = { workspace = true }
serde_json        = { workspace = true }
thiserror         = { workspace = true }
anyhow            = { workspace = true }
tracing           = { workspace = true }
