[package]
name    = "vms-actions"
version = "0.1.0"
edition = "2021"

[dependencies]
vms-core       = { path = "../vms-core" }
vms-media      = { path = "../vms-media" }
gstreamer      = { workspace = true }
gstreamer-app  = { workspace = true }
tokio      = { workspace = true }
serde_json = { workspace = true }
uuid       = { workspace = true }
chrono     = { workspace = true }
minijinja  = { workspace = true }
aes-gcm    = { workspace = true }
rand       = { workspace = true }
base64     = { workspace = true }
thiserror  = { workspace = true }
anyhow     = { workspace = true }
tracing    = { workspace = true }
