[package]
name    = "vms-daemon"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "vms-daemon"
path = "src/main.rs"

[dependencies]
vms-core       = { path = "../vms-core" }
vms-db         = { path = "../vms-db" }
vms-media      = { path = "../vms-media" }
vms-sources    = { path = "../vms-sources" }
vms-engine     = { path = "../vms-engine" }
vms-api        = { path = "../vms-api" }
tokio             = { workspace = true }
salvo             = { workspace = true }
figment           = { workspace = true }
serde             = { workspace = true }
sea-orm           = { workspace = true }
sea-orm-migration = { workspace = true }
tracing           = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow            = { workspace = true }
