[package]
name    = "vms-engine"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
vms-core       = { path = "../vms-core" }
vms-db         = { path = "../vms-db" }
vms-media      = { path = "../vms-media" }
vms-sources    = { path = "../vms-sources" }
vms-actions    = { path = "../vms-actions" }
vms-transports = { path = "../vms-transports" }
tokio          = { workspace = true }
tokio-util     = { workspace = true }
dashmap        = { workspace = true }
arc-swap       = { workspace = true }
evalexpr       = { workspace = true }
tokio-cron-scheduler = { workspace = true }
sysinfo              = { workspace = true }
serde          = { workspace = true }
serde_json     = { workspace = true }
uuid           = { workspace = true }
chrono         = { workspace = true }
chrono-tz      = { workspace = true }
thiserror      = { workspace = true }
anyhow         = { workspace = true }
tracing        = { workspace = true }
prometheus     = { workspace = true }
gstreamer         = { workspace = true }
gstreamer-pbutils = { workspace = true }

[dev-dependencies]
sea-orm = { workspace = true }
tokio   = { workspace = true, features = ["test-util"] }
