[package]
name    = "vms-api"
version = "0.1.0"
edition = "2021"

[dependencies]
vms-core   = { path = "../vms-core" }
vms-db     = { path = "../vms-db" }
vms-media  = { path = "../vms-media" }
vms-engine = { path = "../vms-engine" }
tokio      = { workspace = true }
salvo      = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
uuid       = { workspace = true }
chrono     = { workspace = true }
thiserror  = { workspace = true }
anyhow     = { workspace = true }
tracing    = { workspace = true }
